### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by warwolf7** [home-climate-control/dz#107]
- Action taken: visited [https://www.homeclimatecontrol.com/hardware](https://www.homeclimatecontrol.com/hardware)

- Expected result : link in this line 

> Various [DS2408](https://www.google.com/url?q=https%3A%2F%2Fwww.maximintegrated.com%2Fen%2Fproducts%2Fdigital%2Fmemory-products%2FDS2408.html&sa=D&sntz=1&usg=AFQjCNF4RejFSvMfBF59jtZoZG-Zw03DSg
) based relay boards;

to be leading to DS2408 relay boards products

- Action result: maxime integrated website shows error 404

:skull:

**Comment by climategadgets** [comment]
Fixed, finally :facepalm: 
The original link never lead to relay board products, but to DS2408 description, which has been moved to https://www.maximintegrated.com/en/products/ibutton-one-wire/memory-products/DS2408.html since.
