### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by warwolf7** [home-climate-control/dz#108]
- Action taken: visited [https://www.homeclimatecontrol.com/hardware](https://www.homeclimatecontrol.com/hardware)

- Expected result: link in this line:

> Any hardware that can deliver its readings via stdout is supported. This includes all devices supported by [lm_sensors](http://www.google.com/url?q=http%3A%2F%2Fwww.lm-sensors.org%2F&sa=D&sntz=1&usg=AFQjCNH9tJ_1hfaXxersyB-LGyA-teyFfw)

To be showing a webpage with a description of lm_sensors

- Actual result: webpage does not load. I believe the domain lm-sensors.org does not exist anymore. Maybe this [link](https://en.wikipedia.org/wiki/Lm_sensors) is what we are looking for

 :skull:

**Comment by climategadgets** [comment]
Fixed, finally, along with many others :facepalm:
