### ISSUE TITLE
Change path to commons-codec in classpath

### ISSUE THREAD

**Issue by marcass** [home-climate-control/dz#17]
HI Vadim, I can't create a pull request as not authorised to push to repo, so can you please change this line in dz3-shell/classpath:
${LIBDIR}/commons-codec-1.2.jar:\

to:
${LIBDIR}/commons-codec-1.3.jar:\

Cheers!

Marcus

**Comment by climategadgets** [comment]
Fixed in d70e5b2c508ac76d5cf391539565305aea8e1d7d
