### ISSUE TITLE
Sample google calendar has no detail info.

### ISSUE THREAD

**Issue by jbuszkie** [home-climate-control/dz#27]
The google calendar provided in the example here:
http://diy-zoning.blogspot.com/2010/01/faq-how-schedule-periods-work.html

Doesn't have any detail.  It's show as locked. 
So the calendar needs to be updated to be "open"
Or the guide needs more detail on how to set it up....
Or I'm an idiot and I can't seem to see the details of the events! :-)

**Comment by climategadgets** [comment]
Fixed. Root cause: Google tightening account permissions with time, sharing settings for the calendar had to be relaxed.
