### ISSUE TITLE
GCal set schedule not updating app

### ISSUE THREAD

**Issue by marcass** [home-climate-control/dz#46]
Problem: Host machine restart broke schedule update in app. Restart was for a problem with another project (not dz related).

Git branch version:
`$ git branch -v
* master fdb03bd [ahead 4, behind 46] new version Merge branch 'master' of https://github.com/home-climate-control/dz`

Steps taken to resolve:
- Renew {HOME}/.dz/Calendar/StoredCredential in case it had expired (have to run "$./dz-runner <conf> | grep https" to get url, local port forward to headless machine the port specified in the authentication URL, paste url in local browser and sign in. SortedCredential was verified as updated) => no success
- Renew app-specific password in dz3 conf file in the http-connector section => no success
- restart dz service => no success
- restart machine => no success

The error (occurs every minute in logs) is:

16:01:10,052 ERROR Scheduler pool-13-thread-1 [run] Unexpected exception 
java.util.NoSuchElementException 
       at java.util.StringTokenizer.nextToken(StringTokenizer.java:349) 
       at net.sf.dz3.scheduler.gcal.StatusParser.parse(StatusParser.java:77) 
       at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.parseEvent(GCalScheduleUpdater.java:322) 
       at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.updateEvent(GCalScheduleUpdater.java:290) 
       at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.parse(GCalScheduleUpdater.java:261) 
       at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.parseEvents(GCalScheduleUpdater.java:243) 
       at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.updateCalendar(GCalScheduleUpdater.java:181) 
       at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.update(GCalScheduleUpdater.java:126) 
       at net.sf.dz3.scheduler.Scheduler.update(Scheduler.java:265) 
       at net.sf.dz3.scheduler.Scheduler.run(Scheduler.java:229) 
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) 
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) 
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) 
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
       at java.lang.Thread.run(Thread.java:745)

**Comment by marcass** [comment]
Setpoints set in google calendar with following sytnax:
background: setpoint 10C, disabled
home: setpoint 18C
and variations thereof

**Comment by marcass** [comment]
Solved. See bold calendar entry - syntax was incorrect.

With current code run in precompiled (using classpath, not classpath-dev) code I get the following error with info detail preceding error:

08:58:13,565 INFO Scheduler pool-14-thread-1 [run] Checking schedule                                                                                                                                                 
08:58:14,347 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update] 10 calendars found:                                                                                                                     
08:58:14,349 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: spare bed                                                                                                                   
08:58:14,350 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: kids bed                                                                                                                    
08:58:14,351 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: outside                                                                                                                     
08:58:14,353 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: living                                                                                                                      
08:58:14,354 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: coffee                                                                                                                      
08:58:14,354 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: hall                                                                                                                        
08:58:14,355 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: marcus bed                                                                                                                  
08:58:14,356 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: downstairs                                                                                                                  
08:58:14,357 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: Contacts                                                                                                                    
08:58:14,358 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: Holidays in New Zealand                                                                                                     
08:58:14,360 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar] Zone name: spare bed                                                                                                    
08:58:14,361 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar] id: <some-token-i've-removed for bug report>@group.calendar.google.com                                                                
08:58:14,364 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents] query: {calendarId=<some-token-i've-removed for bug report>@group.calendar.google.com, singleEvents=true, timeMax=2018-07-31T23:59:59.000+12:00, timeMin=2018-07-31T00:00:00.000+12:00}                                                                                                                                                       
08:58:14,915 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents] 1 events found                                                                                             
08:58:14,917 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent]   {"date":"2018-07-31"} to {"date":"2018-08-01"}                                              
08:58:14,917 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod] name: 'background'                                                               
08:58:14,922 INFO StatusParser pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod, parse] Token: 'setpoint 10c'                                                            
08:58:14,923 INFO StatusParser pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod, parse] Token: 'disabled'                                                                
08:58:14,927 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar] Zone name: kids bed                                                                                                     
08:58:14,928 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar] id: wells.heating@gmail.com                                                                                             
08:58:14,931 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents] query: {calendarId=wells.heating@gmail.com, singleEvents=true, timeMax=2018-07-31T23:59:59.000+12:00, timeMin=2018-07-31T00:00:00.000+12:00}                                                                                                                                                                                    
08:58:15,468 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents] 1 events found                                                                                             
08:58:15,470 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent]   {"date":"2018-07-31"} to {"date":"2018-08-01"}                                              
08:58:15,471 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod] name: 'background'                                                               
08:58:15,476 INFO StatusParser pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod, parse] Token: 'setpoint 10c'                                                            
08:58:15,477 INFO StatusParser pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod, parse] Token: 'disabled'                                                                
08:58:15,482 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar] Zone name: outside                                                                                                      
08:58:15,483 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar] id: 31s9p9komk16gaaj9n2mukurjs@group.calendar.google.com                                                                
08:58:15,486 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents] query: {calendarId=31s9p9komk16gaaj9n2mukurjs@group.calendar.google.com, singleEvents=true, timeMax=2018-07-31T23:59:59.000+12:00, timeMin=2018-07-31T00:00:00.000+12:00}                                                                                                                                                       
08:58:16,036 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents] 1 events found                                                                                             
08:58:16,038 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent]   {"date":"2018-07-31"} to {"date":"2018-08-01"}                                              
08:58:16,039 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod] name: 'background'   

**Error in here:**                                                            
08:58:16,043 INFO StatusParser pool-14-thread-1 [run, update, update, updateCalendar, parseEvents, updateEvent, parsePeriod, parse] Token: '**setpoint10c**'          

                                                   
08:58:16,047 ERROR Scheduler pool-14-thread-1 [run] Unexpected exception
 java.util.NoSuchElementException: null
        at java.util.StringTokenizer.nextToken(StringTokenizer.java:349) ~[?:1.8.0_112]
        at net.sf.dz3.scheduler.gcal.StatusParser.parse(StatusParser.java:78) ~[dz3-scheduler-gcal-v3-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.parseEvent(GCalScheduleUpdater.java:322) ~[dz3-scheduler-gcal-v3-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.updateEvent(GCalScheduleUpdater.java:290) ~[dz3-scheduler-gcal-v3-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.parse(GCalScheduleUpdater.java:261) ~[dz3-scheduler-gcal-v3-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.parseEvents(GCalScheduleUpdater.java:243) ~[dz3-scheduler-gcal-v3-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.updateCalendar(GCalScheduleUpdater.java:181) ~[dz3-scheduler-gcal-v3-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.gcal.GCalScheduleUpdater.update(GCalScheduleUpdater.java:126) ~[dz3-scheduler-gcal-v3-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.Scheduler.update(Scheduler.java:266) ~[dz3-scheduler-3.6.8-SNAPSHOT.jar:?]
        at net.sf.dz3.scheduler.Scheduler.run(Scheduler.java:230) [dz3-scheduler-3.6.8-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_112]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_112]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
08:58:16,051 INFO Scheduler pool-14-thread-1 [run] done
08:59:13,565 INFO Scheduler pool-14-thread-1 [run] Checking schedule                                                                                                                                                 
08:59:14,331 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update] 10 calendars found:                                                                                                                     
08:59:14,332 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: spare bed                                                                                                                   
08:59:14,333 INFO GCalScheduleUpdater pool-14-thread-1 [run, update, update]   calendar: kids bed    

Sorry for not spotting this!

marcus

**Comment by marcass** [comment]
In summary, calendar items with a syntax like this:
<label>: setpoint10C
Will throw an exception as it won't parse. There needs to be a space between 'setpoint' and <value>, like so:
<label>: setpoint 10C

I should read the docs more carefully!

**Comment by climategadgets** [comment]
Parser will be updated to issue a clearer message to indicate what exactly made it choke.

**Comment by climategadgets** [comment]
Added a Wiki page to aid in schedule configuration: https://github.com/home-climate-control/dz/wiki/Schedule:-Google-Calendar-Integration:-Syntax
