### ISSUE TITLE
Unable to create bean with 'http-connector-v3' on freshly built dz installaton

### ISSUE THREAD

**Issue by marcass** [home-climate-control/dz#81]
Using this to build system:

#! /bin/sh

cd /home/mw/git/dz-build1/

git clone https://github.com/climategadgets/jukebox
(cd jukebox && mvn install -Dmaven.test.skip)

git clone https://github.com/climategadgets/servomaster
(cd servomaster && mvn install -Dmaven.test.skip)

# Note that you can this skip this test to use the original xbee-api
# (from https://github.com/andrewrapp/xbee-api). However, it's recommended
# to use this version - it has some improvements that the original doesn't have.
# Hopefully, at some point in the future they will merge back together.
git clone https://github.com/home-climate-control/xbee-api
(cd xbee-api/ && mvn install -Dmaven.test.skip)

git clone https://github.com/home-climate-control/dz
# If you're inclined to run this with tests, either install a browser that works
# (Midori works for me, sometimes), or follow these instructions:
# https://github.com/home-climate-control/dz/wiki/HOWTO:-Google-calendar-on-headless-system
(cd dz/dz3-master && mvn install -Dmaven.test.skip)

Getting this error when running:
16:08:09,928 FATAL Container main [run] Unexpected exception: 
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'http-connector-v3' defined in class path resource [dz_connector.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [net.sf.dz3.view.http.v3.HttpConnector]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/gson/Gson

This is the part of the conf file for the v3 connector:
  
     
        <bean id="http-connector-v3" class="net.sf.dz3.view.http.v3.HttpConnector" init-method="activate">
                <constructor-arg index="0" value="https://home-climate-control-v3.appspot.com/v3/data-source" />
                <constructor-arg index="1" type="java.util.Set">
                        <set>
                                <ref bean="thermostat-reception"/>
                                <ref bean="thermostat-surgery"/>
                                <ref bean="thermostat-kennels"/>
                        </set>
                </constructor-arg>
        </bean>

Builds fine on another system (different conf file).

Any suggestions?! Tearing my hair out over this

Thanks

**Comment by climategadgets** [comment]
No longer relevant - shell scripts are now composed automatically, bugs of this kind are no longer possible.
