### ISSUE TITLE
Provide ability to authenticate MQTT connection

### ISSUE THREAD

**Issue by TIKProperties** [home-climate-control/dz#82]
In my scenario the MQTT broker is on the local network and is safeguarded by additional ACLs so allowing unauthenticated publis might not be such a bad deal, but I can imagine many use cases (bigger networks with "guest" devices) where this might be an issue. Especially when DZ starts accepting commands.

Therefore: 
 
Please provide ability to publish to MQTT brokers that disallow anonymous connections.

**Comment by climategadgets** [comment]
For now, accepting empty passwords but issuing a warning into the log, in the future, will fast fail if the password is empty or not provided - that defeats the purpose, and may lull the user into a false sense of security.
